version: 2.1
workflows:
  test_app:
    jobs:
      - build
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run: source /home/circleci/.bashrc
      - run: yarn
      - run: yarn images:pull
