version: 2.1
workflows:
  test_app:
    jobs:
      - build
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run: source /home/circleci/.bashrc
      - run: yarn
      - run: yarn images:pull
      - run: yarn lint
      - run:
          name: Build
          command: yarn build
          no_output_timeout: 30m
      - run: yarn test
